# Generated by Django 4.2.5 on 2024-06-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluemountapp', '0002_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
